.\" Process this file with
.\" groff -man -Tascii proton-picker-run.1
.\"
.\" t
.Dd 2025/11/13             \" DATE
.Dt proton-picker-run  \" Program name and manual section number
.Sh NAME        \" Section Header - required - don't modify
.Nm proton-picker-run
.Nd The "run with" proton utility.
.Sh SYNOPSIS             \" Section Header
.Nm
name                     \" Arguments
.Sh DESCRIPTION          \" Section Header
The utility
.Nm
integrates with the KDE right click menu to allow running any arbitrary
Microsoft Windows executbale using any of the installed proton runners


.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/Users/homeuser" -compact
.It Pa /usr/local/bin/
.Nm
\/.sh
.It Pa $HOME/.local/share/kio/servicemenus/
.Nm
\/.desktop
.It Pa $HOME/.steam/steam/compatibilitytools.d/
For the ProtonPlus installed runners.
.El                      \" Ends the list
